<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
@extends('layouts.master')

@section('title')
    Requisitos
@stop

@section('content')
    @if (Session::has('message'))
    {{Session::get('message')}}
    @endif
    <h1>Requisitos Legales de la empresa</h1>
        <p>Los Requisitos legales del medio ambiente para la empresa:</p>

        {{HTML::ul($requisites)}}
        
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
          <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
        <p> esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla esto es una maravilla </p>
          
        
        
@stop

@section('menulateral')
@include('includes.sidebar')
@stop

@section('boton')
<button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
@stop

